# Generated by Django 5.0.6 on 2024-07-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="cusine_types",
            new_name="cuisine_types",
        ),
    ]
